apiVersion: v1
kind: Service
metadata:
  name: sip-service
  namespace: livekit
spec:
  type: LoadBalancer  # Para exponer SIP URI externamente (e.g., sip:$MINIKUBE_IP:5060)
  ports:
  - name: udp  # Nombre requerido para puerto UDP
    port: 5060
    targetPort: 5060
    protocol: UDP
  - name: tcp  # Nombre requerido para puerto TCP (para signaling TLS si lo usas)
    port: 5060
    targetPort: 5060
    protocol: TCP
  selector:
    app: sip