# values-ingress.yaml
api_key: devkey
api_secret: secret
ws_url: ws://livekit-server:7880
redis:
  address: livekit-redis-master:6379
rtmp_port: 1935
whip_port: 8080
rtc_config:
  udp_port: 7885
  use_external_ip: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60